version: "3.9"
services:
  spring-boot-helloworld:
    build: .
    image: "${IMAGE_NAME}:${IMAGE_TAG}"
    ports:
      - "8080:8080"
  smoke-test:
    image: "curlimages/curl"
    command:
      [
        "--retry-connrefused",
        "--retry",
        "5",
        "-s",
        "http://spring-boot-helloworld:8080"
      ]
    depends_on:
      - spring-boot-helloworld
